/**
 * A scattered point-cloud silhouette generated by sampling a rotated
 * ellipsoid surface with jitter and depth-based size/opacity — a stand-in
 * for the reconstructed geometry, not a stock icon.
 */
function PointCloudVisual({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 480 280"
      fill="currentColor"
      className={className}
      preserveAspectRatio="xMidYMid meet"
      role="img"
      aria-label="Reconstructed 3D point cloud"
    >
        <circle cx="243.1" cy="124.5" r="2.32" opacity="0.81" />
        <circle cx="246.0" cy="132.2" r="1.03" opacity="0.28" />
        <circle cx="239.7" cy="130.7" r="2.35" opacity="0.82" />
        <circle cx="304.4" cy="137.6" r="2.24" opacity="0.77" />
        <circle cx="268.6" cy="192.4" r="1.73" opacity="0.56" />
        <circle cx="274.3" cy="137.3" r="1.02" opacity="0.27" />
        <circle cx="324.4" cy="129.8" r="1.92" opacity="0.64" />
        <circle cx="302.7" cy="134.9" r="1.2" opacity="0.34" />
        <circle cx="241.0" cy="178.8" r="0.95" opacity="0.24" />
        <circle cx="293.9" cy="133.1" r="1.16" opacity="0.33" />
        <circle cx="243.7" cy="122.3" r="2.3" opacity="0.8" />
        <circle cx="300.9" cy="145.5" r="2.26" opacity="0.78" />
        <circle cx="192.8" cy="115.6" r="1.73" opacity="0.56" />
        <circle cx="248.8" cy="186.9" r="1.02" opacity="0.27" />
        <circle cx="280.2" cy="194.4" r="1.38" opacity="0.42" />
        <circle cx="334.0" cy="164.0" r="1.33" opacity="0.4" />
        <circle cx="280.6" cy="149.2" r="0.96" opacity="0.24" />
        <circle cx="219.6" cy="166.4" r="2.31" opacity="0.8" />
        <circle cx="306.2" cy="117.4" r="1.86" opacity="0.62" />
        <circle cx="327.0" cy="129.7" r="1.59" opacity="0.5" />
        <circle cx="187.0" cy="129.8" r="2.04" opacity="0.69" />
        <circle cx="205.9" cy="148.7" r="2.29" opacity="0.8" />
        <circle cx="258.0" cy="133.1" r="2.36" opacity="0.82" />
        <circle cx="269.7" cy="111.9" r="1.54" opacity="0.49" />
        <circle cx="346.0" cy="158.3" r="1.58" opacity="0.5" />
        <circle cx="322.4" cy="172.4" r="1.22" opacity="0.35" />
        <circle cx="237.6" cy="197.9" r="1.61" opacity="0.51" />
        <circle cx="239.7" cy="178.5" r="0.97" opacity="0.25" />
        <circle cx="203.4" cy="135.6" r="2.24" opacity="0.77" />
        <circle cx="225.2" cy="194.2" r="1.61" opacity="0.51" />
        <circle cx="259.1" cy="120.3" r="1.27" opacity="0.37" />
        <circle cx="324.9" cy="144.4" r="2.01" opacity="0.68" />
        <circle cx="282.0" cy="159.1" r="0.95" opacity="0.24" />
        <circle cx="257.4" cy="174.4" r="0.93" opacity="0.23" />
        <circle cx="309.3" cy="180.2" r="1.22" opacity="0.35" />
        <circle cx="157.0" cy="166.6" r="1.58" opacity="0.5" />
        <circle cx="199.1" cy="146.8" r="2.28" opacity="0.79" />
        <circle cx="276.9" cy="170.8" r="2.27" opacity="0.79" />
        <circle cx="160.6" cy="167.4" r="1.72" opacity="0.56" />
        <circle cx="200.4" cy="189.3" r="1.7" opacity="0.55" />
        <circle cx="324.3" cy="182.1" r="1.49" opacity="0.46" />
        <circle cx="260.6" cy="124.4" r="2.28" opacity="0.79" />
        <circle cx="261.5" cy="146.3" r="2.4" opacity="0.84" />
        <circle cx="194.7" cy="175.1" r="1.14" opacity="0.32" />
        <circle cx="323.5" cy="169.3" r="1.96" opacity="0.66" />
        <circle cx="243.0" cy="132.1" r="1.04" opacity="0.28" />
        <circle cx="185.9" cy="158.6" r="2.13" opacity="0.73" />
        <circle cx="282.7" cy="182.6" r="2.03" opacity="0.69" />
        <circle cx="249.2" cy="190.3" r="1.04" opacity="0.28" />
        <circle cx="239.6" cy="130.0" r="2.32" opacity="0.81" />
        <circle cx="273.3" cy="174.1" r="0.96" opacity="0.24" />
        <circle cx="191.2" cy="132.9" r="2.21" opacity="0.76" />
        <circle cx="244.6" cy="182.6" r="0.96" opacity="0.25" />
        <circle cx="166.5" cy="162.1" r="1.89" opacity="0.63" />
        <circle cx="179.3" cy="158.4" r="1.13" opacity="0.32" />
        <circle cx="338.3" cy="155.1" r="1.42" opacity="0.44" />
        <circle cx="333.7" cy="176.1" r="1.57" opacity="0.5" />
        <circle cx="252.5" cy="180.3" r="0.99" opacity="0.26" />
        <circle cx="181.9" cy="146.2" r="1.14" opacity="0.32" />
        <circle cx="300.5" cy="120.3" r="2.02" opacity="0.68" />
        <circle cx="171.3" cy="181.6" r="1.6" opacity="0.51" />
        <circle cx="268.0" cy="196.9" r="1.43" opacity="0.44" />
        <circle cx="212.6" cy="114.5" r="1.85" opacity="0.61" />
        <circle cx="336.4" cy="171.0" r="1.87" opacity="0.62" />
        <circle cx="299.4" cy="148.1" r="2.27" opacity="0.79" />
        <circle cx="273.8" cy="165.2" r="0.93" opacity="0.23" />
        <circle cx="288.0" cy="146.9" r="1.03" opacity="0.27" />
        <circle cx="250.8" cy="126.5" r="2.34" opacity="0.81" />
        <circle cx="237.5" cy="169.5" r="0.92" opacity="0.23" />
        <circle cx="319.5" cy="182.0" r="1.71" opacity="0.56" />
        <circle cx="239.5" cy="110.0" r="2.03" opacity="0.69" />
        <circle cx="225.2" cy="175.6" r="0.99" opacity="0.26" />
        <circle cx="182.6" cy="153.1" r="2.2" opacity="0.76" />
        <circle cx="207.1" cy="116.5" r="1.96" opacity="0.66" />
        <circle cx="243.7" cy="132.4" r="2.35" opacity="0.82" />
        <circle cx="328.1" cy="137.2" r="1.38" opacity="0.42" />
        <circle cx="269.7" cy="145.7" r="2.38" opacity="0.83" />
        <circle cx="264.1" cy="159.3" r="0.9" opacity="0.22" />
        <circle cx="251.9" cy="145.1" r="2.4" opacity="0.84" />
        <circle cx="175.0" cy="186.0" r="1.54" opacity="0.49" />
        <circle cx="256.7" cy="180.0" r="0.94" opacity="0.24" />
        <circle cx="315.9" cy="178.7" r="1.21" opacity="0.35" />
        <circle cx="264.5" cy="160.3" r="0.9" opacity="0.22" />
        <circle cx="259.8" cy="121.0" r="2.21" opacity="0.76" />
        <circle cx="258.0" cy="193.6" r="1.22" opacity="0.35" />
        <circle cx="262.9" cy="109.0" r="1.99" opacity="0.67" />
        <circle cx="235.2" cy="188.8" r="1.12" opacity="0.31" />
        <circle cx="197.7" cy="118.9" r="1.65" opacity="0.53" />
        <circle cx="284.0" cy="123.0" r="2.26" opacity="0.78" />
        <circle cx="313.4" cy="130.1" r="2.06" opacity="0.7" />
        <circle cx="240.0" cy="109.3" r="1.79" opacity="0.59" />
        <circle cx="179.8" cy="185.7" r="1.67" opacity="0.54" />
        <circle cx="271.5" cy="180.3" r="0.97" opacity="0.25" />
        <circle cx="244.5" cy="131.3" r="1.04" opacity="0.28" />
        <circle cx="207.0" cy="116.3" r="1.79" opacity="0.59" />
        <circle cx="233.9" cy="108.7" r="1.82" opacity="0.6" />
        <circle cx="185.7" cy="155.6" r="2.2" opacity="0.76" />
        <circle cx="326.3" cy="156.6" r="1.19" opacity="0.34" />
        <circle cx="216.7" cy="191.2" r="1.82" opacity="0.6" />
        <circle cx="169.4" cy="175.4" r="1.6" opacity="0.51" />
        <circle cx="195.3" cy="145.8" r="2.26" opacity="0.78" />
        <circle cx="259.8" cy="114.2" r="2.1" opacity="0.72" />
        <circle cx="197.9" cy="119.4" r="1.8" opacity="0.59" />
        <circle cx="219.1" cy="109.6" r="2.01" opacity="0.68" />
        <circle cx="255.4" cy="185.9" r="1.99" opacity="0.67" />
        <circle cx="173.8" cy="183.1" r="1.51" opacity="0.47" />
        <circle cx="186.4" cy="132.8" r="2.16" opacity="0.74" />
        <circle cx="246.8" cy="147.5" r="0.93" opacity="0.23" />
        <circle cx="255.2" cy="179.7" r="0.99" opacity="0.26" />
        <circle cx="249.5" cy="195.9" r="1.16" opacity="0.33" />
        <circle cx="248.6" cy="181.5" r="0.94" opacity="0.24" />
        <circle cx="319.1" cy="140.6" r="1.23" opacity="0.36" />
        <circle cx="297.4" cy="127.3" r="1.29" opacity="0.38" />
        <circle cx="180.8" cy="142.2" r="2.16" opacity="0.74" />
        <circle cx="259.8" cy="116.7" r="1.31" opacity="0.39" />
        <circle cx="312.0" cy="150.6" r="2.19" opacity="0.75" />
        <circle cx="209.5" cy="128.8" r="2.25" opacity="0.78" />
        <circle cx="243.8" cy="122.5" r="2.27" opacity="0.79" />
        <circle cx="200.4" cy="148.7" r="2.29" opacity="0.79" />
        <circle cx="186.8" cy="155.2" r="1.13" opacity="0.31" />
        <circle cx="247.2" cy="131.4" r="2.35" opacity="0.82" />
        <circle cx="257.2" cy="176.5" r="0.93" opacity="0.23" />
        <circle cx="162.9" cy="149.6" r="1.35" opacity="0.4" />
        <circle cx="240.5" cy="131.7" r="2.35" opacity="0.82" />
        <circle cx="211.3" cy="139.7" r="2.33" opacity="0.81" />
        <circle cx="243.1" cy="127.3" r="2.32" opacity="0.81" />
        <circle cx="329.3" cy="170.3" r="1.39" opacity="0.42" />
        <circle cx="329.4" cy="154.1" r="1.99" opacity="0.67" />
        <circle cx="257.7" cy="112.6" r="1.63" opacity="0.52" />
        <circle cx="245.4" cy="139.5" r="2.39" opacity="0.84" />
    </svg>
  );
}

export { PointCloudVisual };
